{pkgs}:
with pkgs.vimPlugins; [
  cyberdream-nvim
  telescope-nvim
  telescope-recent-files
  undotree
  vim-fugitive
  nvim-lspconfig
  lsp-zero-nvim
  nvim-cmp
  cmp-buffer
  cmp-nvim-lsp
  cmp-nvim-lua
  cmp-path
  cmp_luasnip
  luasnip
  copilot-lua
  copilot-cmp
  lspkind-nvim
  nvim-treesitter.withAllGrammars
] 
